"""Bounded 8x16 OBJ packets with column masks and double-buffered patterns."""
from .layout import *  # noqa: F401,F403


def emit_masked_entities(a: Assembler) -> None:
    a.label("choose_entity_lod")
    a.ld_a_abs(ENTITY_SLOT); a.ld_r_r("e", "a"); a.ld_r_n("d", 0); a.ld_rr_nn("hl", LOD_HISTORY); a.add_hl_rr("de")
    a.ld_a_hl(); a.ld_r_r("b", "a"); a.ld_a_abs(ENTITY_FORWARD)
    a.cp_n(28); a.jr("lod_near", "c"); a.cp_n(68); a.jr("lod_far", "nc")
    a.ld_r_r("c", "a"); a.ld_r_r("a", "b"); a.or_r("a"); a.jr("lod_not_near", "nz")
    a.ld_r_r("a", "c"); a.cp_n(36); a.jr("lod_near", "c")
    a.label("lod_not_near"); a.ld_r_r("a", "b"); a.cp_n(2); a.jr("lod_mid", "nz")
    a.ld_r_r("a", "c"); a.cp_n(60); a.jr("lod_far", "nc")
    a.label("lod_mid"); a.ld_r_n("a", 1); a.jr("lod_store")
    a.label("lod_near"); a.xor_r("a"); a.jr("lod_store")
    a.label("lod_far"); a.ld_r_n("a", 2)
    a.label("lod_store"); a.ld_hl_a(); a.ld_abs_a(SENTINEL_LOD); a.ret()

    a.label("submit_masked_oam")  # B=Y, C=X, D=even source cel, E=palette
    for source, target in (("b", MASK_OAM_Y), ("c", MASK_OAM_X), ("d", MASK_SOURCE_TILE), ("e", MASK_ATTRIBUTES)):
        a.ld_r_r("a", source); a.ld_abs_a(target)
    a.ld_a_abs(MASK_BITS); a.or_r("a"); a.ret("z")
    a.ld_a_abs(SENTINEL_OAM_USED); a.cp_n(ENTITY_OAM_COUNT); a.ret("nc")
    a.ld_a_abs(MASK_OAM_Y); a.or_r("a"); a.ret("z"); a.cp_n(160); a.ret("nc")
    a.sub_n(16); a.jr("mask_scan_start_ready", "nc"); a.xor_r("a")
    a.label("mask_scan_start_ready"); a.ld_abs_a(MASK_SCAN_START)
    a.ld_r_r("b", "a"); a.ld_a_abs(MASK_OAM_Y); a.cp_n(144); a.jr("mask_scan_end_ready", "c"); a.ld_r_n("a", 144)
    a.label("mask_scan_end_ready"); a.sub_r("b"); a.ld_abs_a(MASK_SCAN_COUNT); a.ld_r_r("c", "a")
    a.ld_r_r("l", "b"); a.ld_r_n("h", WORLD_SCANLINES >> 8)
    a.label("mask_preflight_loop")
    # Reserving six UI-selected objects leaves four world objects on every
    # scanline, including rows occupied by the weapon/crosshair/muzzle.
    a.ldi_a_hl(); a.cp_n(4); a.ret("nc"); a.dec_r("c"); a.jr("mask_preflight_loop", "nz")
    a.ld_a_abs(MASK_SCAN_START); a.ld_r_r("l", "a"); a.ld_r_n("h", WORLD_SCANLINES >> 8)
    a.ld_a_abs(MASK_SCAN_COUNT); a.ld_r_r("c", "a")
    a.label("mask_reserve_loop"); a.inc_r("(hl)"); a.inc_rr("hl"); a.dec_r("c"); a.jr("mask_reserve_loop", "nz")
    a.ld_a_abs(MASK_TILE_COUNT); a.ld_r_r("l", "a"); a.ld_r_n("h", 0)
    for _ in range(4): a.add_hl_rr("hl")
    a.ld_rr_nn("de", MASK_TILES); a.add_hl_rr("de"); a.ld_r_r("d", "h"); a.ld_r_r("e", "l")
    a.ld_a_abs(MASK_SOURCE_TILE); a.ld_r_r("l", "a"); a.ld_r_n("h", 0)
    for _ in range(4): a.add_hl_rr("hl")
    a.ld_rr_label("bc", "entity_tiles"); a.add_hl_rr("bc")
    a.ld_r_n("a", BOOT_ASSETS_ROM_BANK); a.ld_abs_a(0x2000)
    a.ld_a_abs(MASK_BITS); a.ld_r_r("b", "a"); a.ld_r_n("c", 32)
    a.label("mask_copy_loop")
    a.ldi_a_hl(); a.and_r("b"); a.ld_mem_rr_a("de"); a.inc_rr("de"); a.dec_r("c"); a.jr("mask_copy_loop", "nz")
    a.ld_r_n("a", 1); a.ld_abs_a(0x2000)
    load_hl_abs(a, ENTITY_OAM_PTR_L, ENTITY_OAM_PTR_H)
    for address in (MASK_OAM_Y, MASK_OAM_X, MASK_TILE_COUNT):
        a.ld_a_abs(address); a.ldi_hl_a()
    a.ld_a_abs(CURRENT_PAGE); a.xor_n(1)
    for _ in range(3): a.add_a_r("a")
    a.ld_r_r("b", "a"); a.ld_a_abs(MASK_ATTRIBUTES); a.and_n(7); a.or_r("b"); a.ldi_hl_a()
    store_hl_abs(a, ENTITY_OAM_PTR_L, ENTITY_OAM_PTR_H)
    a.ld_a_abs(MASK_TILE_COUNT); a.add_a_n(2); a.ld_abs_a(MASK_TILE_COUNT)
    a.ld_a_abs(SENTINEL_OAM_USED); a.inc_r("a"); a.ld_abs_a(SENTINEL_OAM_USED); a.ret()

    a.label("upload_masked_tiles")
    a.ld_a_abs(MASK_TILE_COUNT); a.or_r("a"); a.ret("z"); a.ld_r_r("b", "a")
    a.ld_a_abs(CURRENT_PAGE); a.xor_n(1); a.ldh_n_a(VBK)
    a.ld_r_n("a", MASK_TILES >> 8); a.ldh_n_a(HDMA1)
    a.xor_r("a"); a.ldh_n_a(HDMA2); a.ldh_n_a(HDMA3); a.ldh_n_a(HDMA4)
    a.ld_r_r("a", "b"); a.dec_r("a"); a.ldh_n_a(HDMA5); a.ret()


def emit_entity_renderer_v7(a: Assembler) -> None:
    a.label("render_entities")
    a.call("clear_entity_oam_shadow")
    a.xor_r("a"); a.ld_abs_a(DECAL_PROJECTING)
    a.ld_a_abs(WORLD_MODE); a.or_r("a"); a.jr("render_world_decor", "z")
    a.ld_a_abs(VRAM_PROFILE); a.cp_n(VRAM_PROFILE_ENTITY); a.jr("render_world_decor", "nz")
    a.call("render_actor_slots"); a.call("render_exit_beacon")
    a.label("render_world_decor"); a.jp("render_wall_fixtures")

    a.label("render_sentinel_actor")
    a.call("project_sentinel"); a.ld_a_abs(SENTINEL_VISIBLE); a.or_r("a"); a.ret("z")
    a.ld_a_abs(SENTINEL_LOD); a.cp_n(2); a.jp("render_far_pair", "z")
    a.or_r("a"); a.jp("render_medium_pairs", "nz")
    a.ld_a_abs(SENTINEL_ANIM); a.and_n(3)
    for _ in range(3): a.add_a_r("a")
    a.add_a_n(SENTINEL_NEAR_TILE_BASE); a.ld_abs_a(ENTITY_TILE_BASE_STATE)
    for col, visible in ((0, ENTITY_SCREEN_LEFT), (1, ENTITY_SCREEN_RIGHT)):
        for row in range(2):
            a.ld_a_abs(visible); a.ld_abs_a(MASK_BITS)
            a.ld_a_abs(ENTITY_FOOT_Y); a.sub_n(32 - row * 16); a.ld_r_r("b", "a")
            a.ld_a_abs(SENTINEL_SCREEN_X); a.add_a_n(col * 8); a.ld_r_r("c", "a")
            a.ld_a_abs(ENTITY_TILE_BASE_STATE); a.add_a_n(col * 4 + row * 2); a.ld_r_r("d", "a")
            a.ld_r_n("e", 1); a.call("submit_masked_oam")
    a.ret()
    a.label("render_medium_pairs")
    a.ld_a_abs(SENTINEL_ANIM); a.and_n(1); a.add_a_r("a"); a.add_a_r("a"); a.add_a_n(SENTINEL_MID_TILE_BASE); a.ld_abs_a(ENTITY_TILE_BASE_STATE)
    for col, visible in ((0, ENTITY_SCREEN_LEFT), (1, ENTITY_SCREEN_RIGHT)):
        a.ld_a_abs(visible); a.ld_abs_a(MASK_BITS)
        a.ld_a_abs(ENTITY_FOOT_Y); a.sub_n(16); a.ld_r_r("b", "a")
        a.ld_a_abs(SENTINEL_SCREEN_X); a.add_a_n(col * 8); a.ld_r_r("c", "a")
        a.ld_a_abs(ENTITY_TILE_BASE_STATE); a.add_a_n(col * 2); a.ld_r_r("d", "a")
        a.ld_r_n("e", 1); a.call("submit_masked_oam")
    a.ret()
    a.label("render_far_pair")
    a.ld_a_abs(ENTITY_SCREEN_LEFT); a.ld_abs_a(MASK_BITS)
    a.ld_a_abs(SENTINEL_ANIM); a.and_n(1); a.add_a_r("a"); a.add_a_n(SENTINEL_FAR_TILE_BASE); a.ld_r_r("d", "a")
    a.ld_a_abs(ENTITY_FOOT_Y); a.sub_n(16); a.ld_r_r("b", "a")
    a.ld_a_abs(SENTINEL_SCREEN_X); a.add_a_n(4); a.ld_r_r("c", "a")
    a.ld_r_n("e", 1); a.jp("submit_masked_oam")

    a.label("render_dropped_pickup")
    a.ld_a_abs(PICKUP_ACTIVE); a.or_r("a"); a.ret("z")
    a.call("project_sentinel"); a.ld_a_abs(SENTINEL_VISIBLE); a.or_r("a"); a.ret("z")
    a.ld_a_abs(SENTINEL_SCREEN_X); a.call("entity_column_visible"); a.ld_abs_a(MASK_BITS)
    a.ld_a_abs(ENTITY_FOOT_Y); a.sub_n(8); a.ld_r_r("b", "a")
    a.ld_a_abs(SENTINEL_SCREEN_X); a.add_a_n(4); a.ld_r_r("c", "a")
    a.ld_r_n("d", PICKUP_TILE); a.ld_r_n("e", 2); a.jp("submit_masked_oam")

    a.label("render_exit_beacon")
    a.ld_a_abs(EXIT_ACTIVE); a.or_r("a"); a.ret("z")
    a.ld_r_n("a", 4); a.ld_abs_a(ENTITY_SLOT)
    a.ld_r_n("a", 128); a.ld_abs_a(ENTITY_WORLD_XL); a.ld_abs_a(ENTITY_WORLD_YL)
    a.ld_a_abs(EXIT_CELL_X); a.ld_abs_a(ENTITY_WORLD_XH)
    a.ld_a_abs(EXIT_CELL_Y); a.ld_abs_a(ENTITY_WORLD_YH)
    a.call("project_entity"); a.ld_a_abs(SENTINEL_VISIBLE); a.or_r("a"); a.ret("z")
    a.ld_a_abs(SENTINEL_SCREEN_X); a.call("entity_column_visible"); a.ld_abs_a(MASK_BITS)
    a.ld_a_abs(SENTINEL_AI_PHASE); a.and_n(1); a.add_a_r("a"); a.add_a_n(EXIT_BEACON_TILE); a.ld_r_r("d", "a")
    a.ld_a_abs(ENTITY_FOOT_Y); a.sub_n(8); a.ld_r_r("b", "a")
    a.ld_a_abs(SENTINEL_SCREEN_X); a.add_a_n(4); a.ld_r_r("c", "a")
    a.ld_r_n("e", 4); a.jp("submit_masked_oam")
