"""Physical-query provenance and repeatable wall refinement under one snapshot."""
from .layout import *


def emit_physical_depth(a: Assembler):
    if not PHYSICAL_DEPTH: return
    a.label("clear_physical_depth")
    a.ld_rr_nn("hl",PIXEL_DEPTH_VALID); a.ld_r_n("b",20); a.xor_r("a")
    a.label("physical_clear_valid")
    a.ldi_hl_a(); a.dec_r("b"); a.jr("physical_clear_valid","nz"); a.ret()

    a.label("physical_bit_address")  # PIXEL_INDEX -> DE=byte index, B=bit mask
    a.ld_a_abs(PIXEL_INDEX); a.and_n(7); a.ld_r_r("e","a"); a.ld_r_n("d",0)
    a.ld_rr_label("hl","physical_bit_masks"); a.add_hl_rr("de"); a.ld_a_hl(); a.ld_r_r("b","a")
    a.ld_a_abs(PIXEL_INDEX)
    for _ in range(3): a.cb("srl","a")
    a.ld_r_r("e","a"); a.ret()
    a.label("physical_bit_masks"); a.bytes(bytes(1<<i for i in range(8)),"physical validity bit masks")

    a.label("save_physical_depth")
    a.ld_a_abs(PIXEL_INDEX); a.ld_r_r("e","a"); a.ld_r_n("d",0)
    a.ld_rr_nn("hl",PIXEL_DEPTH); a.add_hl_rr("de"); a.ld_a_abs(DEPTH_RESULT); a.ld_hl_a()
    a.call("physical_bit_address"); a.ld_rr_nn("hl",PIXEL_DEPTH_VALID); a.add_hl_rr("de")
    a.ld_a_hl(); a.or_r("b"); a.ld_hl_a(); a.ret()

    a.label("coverage_mark_strip")  # A=left (wrapping signed byte), B=width
    a.ld_abs_a(COVERAGE_LEFT); a.ld_r_r("a","b"); a.ld_abs_a(COVERAGE_REMAIN)
    a.label("coverage_mark_pixel")
    a.ld_a_abs(COVERAGE_LEFT); a.cp_n(160); a.jr("coverage_mark_next","nc")
    a.ld_abs_a(PIXEL_INDEX); a.call("physical_bit_address")
    a.ld_rr_nn("hl",PHYSICAL_COVERAGE); a.add_hl_rr("de"); a.ld_a_hl(); a.or_r("b"); a.ld_hl_a()
    a.label("coverage_mark_next")
    a.ld_rr_nn("hl",COVERAGE_LEFT); a.inc_r("(hl)")
    a.ld_rr_nn("hl",COVERAGE_REMAIN); a.dec_r("(hl)"); a.jr("coverage_mark_pixel","nz"); a.ret()

    a.label("coverage_mark_actor")
    a.ld_a_abs(SENTINEL_VISIBLE); a.or_r("a"); a.ret("z")
    a.ld_a_abs(SENTINEL_LOD); a.cp_n(2); a.jr("coverage_mark_small","z")
    a.ld_a_abs(SENTINEL_STATE); a.cp_n(SENTINEL_DEAD); a.jr("coverage_mark_small","z")
    a.ld_a_abs(SENTINEL_SCREEN_X); a.sub_n(8); a.ld_r_n("b",16); a.jp("coverage_mark_strip")
    a.label("coverage_mark_small")
    a.ld_a_abs(SENTINEL_SCREEN_X); a.sub_n(4); a.ld_r_n("b",8); a.jp("coverage_mark_strip")

    a.label("prepare_object_coverage")
    a.xor_r("a")
    for address in (REFINEMENT_DIRTY,REFINEMENT_QUERIED,PHYSICAL_DEPTH_MISSING,PHYSICAL_QUERY_COUNT): a.ld_abs_a(address)
    a.ld_rr_nn("hl",PHYSICAL_COVERAGE); a.ld_r_n("b",20)
    a.label("coverage_clear")
    a.ldi_hl_a(); a.dec_r("b"); a.jr("coverage_clear","nz")
    a.ld_r_n("a",1); a.ld_abs_a(COVERAGE_MODE); a.ld_abs_a(DECAL_PROJECTING)
    a.ld_a_abs(WORLD_MODE); a.or_r("a"); a.jp("coverage_fixtures","z")
    a.ld_a_abs(VRAM_PROFILE); a.cp_n(VRAM_PROFILE_ENTITY); a.jp("coverage_fixtures","nz")
    a.call("save_primary_actor")
    a.label("coverage_actor_loop")
    a.ld_a_abs(ACTOR_COUNT); a.or_r("a"); a.jr("coverage_exit","z")
    a.call("actor_load")
    a.ld_a_abs(SENTINEL_STATE); a.cp_n(SENTINEL_DEAD); a.jr("coverage_project_actor","nz")
    a.ld_a_abs(PICKUP_ACTIVE); a.or_r("a"); a.jr("coverage_next_actor","z")
    a.label("coverage_project_actor")
    a.call("project_sentinel")
    a.ld_a_abs(SENTINEL_VISIBLE); a.or_r("a"); a.jr("coverage_next_actor","z")
    # The projection-only pass skips masks and LOD selection for fixtures.
    # Actors still need their own distance LOD before coverage is marked.
    a.call("choose_entity_lod"); a.call("coverage_mark_actor")
    a.label("coverage_next_actor")
    a.call("actor_next"); a.jr("coverage_actor_loop","nz")
    a.label("coverage_exit")
    a.call("restore_primary_actor")
    a.ld_a_abs(EXIT_ACTIVE); a.or_r("a"); a.jr("coverage_fixtures","z")
    a.ld_r_n("a",4); a.ld_abs_a(ENTITY_SLOT)
    a.ld_r_n("a",128); a.ld_abs_a(ENTITY_WORLD_XL); a.ld_abs_a(ENTITY_WORLD_YL)
    a.ld_a_abs(EXIT_CELL_X); a.ld_abs_a(ENTITY_WORLD_XH); a.ld_a_abs(EXIT_CELL_Y); a.ld_abs_a(ENTITY_WORLD_YH)
    a.call("project_entity"); a.ld_a_abs(SENTINEL_VISIBLE); a.or_r("a"); a.jr("coverage_fixtures","z")
    a.call("coverage_mark_small")
    a.label("coverage_fixtures")
    a.call("render_wall_fixtures")
    a.xor_r("a"); a.ld_abs_a(COVERAGE_MODE); a.ld_abs_a(DECAL_PROJECTING); a.ret()

    a.label("refine_physical_depth")
    a.xor_r("a"); a.ld_abs_a(PIXEL_INDEX)
    a.label("physical_query_loop")
    a.call("physical_bit_address")
    a.ld_rr_nn("hl",PHYSICAL_COVERAGE); a.add_hl_rr("de"); a.ld_a_hl(); a.and_r("b"); a.jp("physical_query_next","z")
    a.ld_rr_nn("hl",PIXEL_DEPTH_VALID); a.add_hl_rr("de"); a.ld_a_hl(); a.and_r("b"); a.jp("physical_query_next","nz")
    if FIXED_SIMULATION: a.call("render_yield")
    a.label("physical_missing_query")
    a.call("cast_physical_indexed_prepared")
    a.ld_r_n("a",1); a.ld_abs_a(REFINEMENT_QUERIED)
    a.ld_rr_nn("hl",PHYSICAL_QUERY_COUNT); a.inc_r("(hl)")
    a.ld_a_abs(PIXEL_INDEX); a.ld_r_r("e","a"); a.ld_r_n("d",0)
    # Decoration is derived, so compare the complete undecorated geometric
    # inputs. A changed key already captures any change to base style.
    for array,result in ((PIXEL_TOPS,TOP_RESULT),(PIXEL_KEYS,FACE_RESULT),(PIXEL_ALONG,ALONG_RESULT),
                         (PIXEL_SEGMENT,SEGMENT_RESULT),(PIXEL_SURFACE,SURFACE_RESULT)):
        a.ld_rr_nn("hl",array); a.add_hl_rr("de"); a.ld_a_abs(result); a.cp_r("(hl)")
        a.jr(f"physical_same_{array}","z"); a.ld_r_n("a",1); a.ld_abs_a(REFINEMENT_DIRTY)
        a.label(f"physical_same_{array}")
        a.ld_a_abs(result); a.ld_hl_a()
    a.ld_rr_nn("hl",PIXEL_STYLES); a.add_hl_rr("de"); a.ld_a_abs(STYLE_RESULT); a.ld_hl_a()
    a.call("save_physical_depth")
    a.label("physical_query_next")
    a.ld_rr_nn("hl",PIXEL_INDEX); a.inc_r("(hl)"); a.ld_a_hl(); a.cp_n(160); a.jp("physical_query_loop","c")
    a.ret()

    a.label("restore_base_styles")
    a.ld_rr_nn("hl",PIXEL_KEYS); a.ld_rr_nn("de",PIXEL_STYLES); a.ld_r_n("c",160)
    a.label("restore_style_column")
    a.ldi_a_hl(); a.ld_r_r("b","a"); a.and_n(0x60); a.cp_n(0x60); a.jr("restore_style_door","z")
    a.cp_n(0x40); a.ld_r_n("a",0); a.jr("restore_style_axis","nz"); a.ld_r_n("a",2)
    a.label("restore_style_axis")
    a.cb("bit","b",7); a.jr("restore_style_store","z"); a.inc_r("a"); a.jr("restore_style_store")
    a.label("restore_style_door"); a.ld_r_n("a",4)
    a.label("restore_style_store")
    a.ld_mem_rr_a("de"); a.inc_rr("de"); a.dec_r("c"); a.jr("restore_style_column","nz"); a.ret()

    a.label("refine_full_snapshot")
    a.call("prepare_object_coverage"); a.call("refine_physical_depth")
    a.call("restore_base_styles"); a.jp("decorate_pixel_styles")
    a.label("refine_reused_snapshot")
    a.call("prepare_object_coverage"); a.call("refine_physical_depth")
    a.ld_a_abs(REFINEMENT_QUERIED); a.or_r("a"); a.jr("physical_reuse_result","z")
    a.call("restore_base_styles"); a.call("decorate_pixel_styles")
    a.label("physical_reuse_result")
    a.ld_a_abs(REFINEMENT_DIRTY); a.or_r("a"); a.ret("z")
    a.xor_r("a"); a.ld_abs_a(FRAME_REUSED); a.ld_abs_a(WALL_CACHE_VALID)
    a.ld_r_n("a",1); a.ret()
