#!/usr/bin/env python3
"""Render the allocation ledger as the memory map page of the developer guide.

    python tools/memory_map.py            # rewrite docs/guide/MEMORY_MAP.md from build/build_manifest.json
    python tools/memory_map.py --check    # fail if the page is stale (tools/check_docs.py runs this)

The ledger is `allocation.py`'s machine-checked table, recorded in the build
manifest, so the page can never disagree with what the linker proved: it is
regenerated, not edited. The default configuration's ledger is the one the
page shows; the textured profile adds rows the manifest of that build lists.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "build" / "build_manifest.json"
PAGE = ROOT / "docs" / "guide" / "MEMORY_MAP.md"
SPACES = (("ROM", "ROM (4 MiB MBC5, 256 banks of 16 KiB; addresses are absolute ROM offsets)"),
          ("WRAM0", "Fixed WRAM (`$C000-$CFFF`)"), ("WRAM1", "WRAM bank 1: the render snapshot (`$D000-$DFFF`)"),
          ("WRAM2", "WRAM bank 2: the live world"), ("WRAM3", "WRAM bank 3"), ("WRAM4", "WRAM bank 4"),
          ("WRAM5", "WRAM bank 5: music"), ("HRAM", "HRAM (`$FF80-$FFFE`)"), ("OAM", "OAM (object slots)"),
          ("VRAM0", "VRAM bank 0"), ("VRAM1", "VRAM bank 1"))


def _rom_span(start: int, end: int) -> str:
    bank_a, bank_b = start // 0x4000, (end - 1) // 0x4000
    low = 0x4000 + start % 0x4000 if bank_a else start
    high = 0x4000 + (end - 1) % 0x4000 + 1 if bank_b else end
    if bank_a == bank_b:
        return f"bank {bank_a} `${low:04X}-${high:04X}`"
    return f"banks {bank_a}-{bank_b} (`${low:04X}` in {bank_a} to `${high:04X}` in {bank_b})"


def render(manifest: dict) -> str:
    ledger = manifest["allocation_ledger"]
    lines = ["<!-- Generated by tools/memory_map.py from build/build_manifest.json. Do not edit: rerun the tool. -->",
             "# Memory map", "",
             f"Configuration `{manifest['configuration_id']}`, ledger schema `{ledger['schema']}`.",
             "Every range is inclusive-exclusive, machine-checked for overlap by `tools/lupine3d_v4/allocation.py`",
             "and recorded in the build manifest; `bank_safety.py` proves the MBC5 rule against the emitted image.",
             "A lifetime other than persistent says when the range is meaningful; outside it the bytes are",
             "free for that owner's neighbour in the same sequence.", "",
             "The free byte counts below `$4000` and in the resident half move with every code",
             "change and are read from `build/build_manifest.json` (`allocation_ledger`), not from here;",
             "the linker refuses a build under the 3,000-byte resident reserve.", "",
             "| Budget | Value |", "|---|---:|",
             f"| Free WRAM banks | {', '.join(str(b) for b in ledger['free_wram_banks'])} |",
             f"| Render snapshot copy | {sum(c for _, c in ledger['snapshot_copy_ranges'])} bytes in "
             f"{len(ledger['snapshot_copy_ranges'])} ranges: "
             + ", ".join(f"`${s:04X}`+{c}" for s, c in ledger['snapshot_copy_ranges']) + " |",
             f"| Prepared ray record | {ledger['prepared_record_bytes']} bytes; packet records "
             f"{ledger['packet_records_per_yaw'][0]}-{ledger['packet_records_per_yaw'][1] - 1} |", ""]
    rows = ledger["ranges"]
    for space, title in SPACES:
        mine = sorted((r for r in rows if r["space"] == space), key=lambda r: r["start"])
        if not mine:
            continue
        lines += [f"## {title}", "", "| Range | Bytes | Owner | Lifetime |", "|---|---:|---|---|"]
        for row in mine:
            span = _rom_span(row["start"], row["end"]) if space == "ROM" else f"`${row['start']:04X}-${row['end']:04X}`"
            if space == "OAM":
                span = f"{row['start']}-{row['end']}"
            lines.append(f"| {span} | {row['end'] - row['start']:,} | {row['owner']} | {row.get('lifetime', 'persistent')} |")
        lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--manifest", type=Path, default=MANIFEST)
    parser.add_argument("--output", type=Path, default=PAGE)
    parser.add_argument("--check", action="store_true", help="compare instead of writing")
    args = parser.parse_args(argv)
    if not args.manifest.is_file():
        print(f"no manifest at {args.manifest}: run `make build` first", file=sys.stderr)
        return 2
    text = render(json.loads(args.manifest.read_text()))
    if args.check:
        current = args.output.read_text() if args.output.is_file() else ""
        if current != text:
            print(f"{args.output} is stale: run `python tools/memory_map.py`", file=sys.stderr)
            return 1
        print(f"{args.output} is current")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
